# Generated by Django 4.1.3 on 2023-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItemQuantity',
            new_name='CartItem',
        ),
    ]
