# Generated by Django 4.1.3 on 2023-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
